### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by 8824PPZ** [gleidsonmt/DashboardFx#19]
`GNCarousel can not find ` in Carousel.java
`LauncherImpl can not find ` in App.java

I imported your code into IDEA, I can't compile your project, I am missing a lot of things. Can you ask what your build environment is?

**Comment by Gleidson28** [comment]
![image](https://user-images.githubusercontent.com/24393885/51073456-28442b00-1658-11e9-99e2-81e13383bda1.png)

![image](https://user-images.githubusercontent.com/24393885/51073460-2f6b3900-1658-11e9-9507-6b928ee528a9.png)
