### ISSUE TITLE
Can't open some .fxml files in Scene Builder

### ISSUE THREAD

**Issue by intothesea** [gleidsonmt/DashboardFx#28]
It seems that Scene Builder can't open some .fxml files in this project ,eg. Carousel.fxml. I found that this seems to be due to the fact that scene builder does not recognize the components in GNCarousel. Please tell me how you solved this problem.

**Comment by intothesea** [comment]
Now I can open it with SB for Java 8 .Thanks.

**Comment by vtsaf** [comment]
@intothesea Please tell us, what changed and SB is able to open the fxmls now?
