### ISSUE TITLE
Add models package to module-info

### ISSUE THREAD

**Issue by matkollin** [gleidsonmt/DashboardFx#32]
Inside the `module-info`, add the property:
`exports code.Models;`

**Comment by matkollin** [comment]
@gleidsonmt this will fix your error

**Comment by gleidsonmt** [comment]
Hi, well.. what error are you referring?

**Comment by matkollin** [comment]
From your stream 5 min ago

**Comment by gleidsonmt** [comment]
Ok, an sorry, why I will put the code.Models in module info? is it a feature? explain more, please.. I'm lost

**Comment by matkollin** [comment]
the modul-info is like a pom.xml from maven.
exporting the package will give javafx access to all classes inside of the package.

**Comment by matkollin** [comment]
> the modul-info is like a pom.xml from maven. exporting the package will give javafx access to all classes inside of the package.

The same as you exported the controller package

**Comment by gleidsonmt** [comment]
Oh the first package in tree , right? I think I got the idea

**Comment by matkollin** [comment]
like so:
`module com.example.c482_project {
    requires javafx.controls;
    requires javafx.fxml;


    opens code to javafx.fxml;
    exports code;
    exports code.Controllers;
    exports code.Models;
    opens code.Controllers to javafx.fxml;
}`

**Comment by gleidsonmt** [comment]
is it because you missing any classes in the project? which?

**Comment by matkollin** [comment]
Do you have teamspeak or discord?

**Comment by gleidsonmt** [comment]
I don't know teamspeak, but I have discord, that's my nickname Gleidson#5768
