### ISSUE TITLE
Gradle Jpackage isn't right. Can't run `DashboardFx.exe` but  `DashboardFx.bat` 

### ISSUE THREAD

**Issue by Leo0426** [gleidsonmt/DashboardFx#33]
### Can't run  `DashboardFx.exe` by jpackage gen . Because `ModuleLayer.boot()` can't find the project module.
![image](https://user-images.githubusercontent.com/19218360/226878121-0681ac18-038b-488f-af2e-1844cf3c2e4f.png)

### But, I can run from jpackage runtime folder by `DashboardFx.bat` entrypoint.
![image](https://user-images.githubusercontent.com/19218360/226878662-21e1c9ab-9e9a-4ff5-9628-bb7804aa18a2.png)

**Comment by gleidsonmt** [comment]
Hi, I'm late.. but.. It's the same problem within #36, please read
