### ISSUE TITLE
gradlew doesn't work

### ISSUE THREAD

**Issue by bdw429s** [gleidsonmt/DashboardFx#35]
The `gradlew.bat` file references the non-existent jar
```
set CLASSPATH=%APP_HOME%\gradle\wrapper2\gradle-wrapper2.jar
```
and calls the non-existent main class 
```
org.gradle.wrapper2.GradleWrapperMain
```

Gradle seems to run if I remove the `2`'s so was this just some testing that got committed on accident?

**Comment by gleidsonmt** [comment]
Continue reading.. here #36

**Comment by gleidsonmt** [comment]
I'll continue in here #36
